name: flamejam2025
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.24.0
  flame: ^1.28.0
  flame_audio: ^2.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
